<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.PHzFzC9' shared service.

return $this->privates['.service_locator.PHzFzC9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'scoreboardService' => ['privates', 'App\\Service\\ScoreboardService', 'getScoreboardServiceService', false],
    'submissionService' => ['privates', 'App\\Service\\SubmissionService', 'getSubmissionServiceService', false],
], [
    'scoreboardService' => 'App\\Service\\ScoreboardService',
    'submissionService' => 'App\\Service\\SubmissionService',
]);
