<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.c_zTQV3' shared service.

return $this->privates['.service_locator.c_zTQV3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'assetPackage' => ['privates', 'assets.packages', 'getAssets_PackagesService', false],
    'projectDir' => ['privates', '.value.zrvvYJt', 'get_Value_ZrvvYJtService.php', true],
], [
    'assetPackage' => '?',
    'projectDir' => '?',
]);
