<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Y8uCV8g' shared service.

return $this->privates['.service_locator.Y8uCV8g'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'assetPackage' => ['privates', 'assets.packages', 'getAssets_PackagesService', false],
], [
    'assetPackage' => '?',
]);
