<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.fBvfyQK.App\Entity\Contest' shared service.

include_once $this->targetDirs[3].'/src/Entity/BaseApiEntity.php';
include_once $this->targetDirs[3].'/src/Entity/Contest.php';

return $this->privates['.errored..service_locator.fBvfyQK.App\\Entity\\Contest'] = new \App\Entity\Contest();
