<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.2xMcASS' shared service.

return $this->privates['.service_locator.2xMcASS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'jid' => ['privates', '.errored..service_locator.2xMcASS.App\\Entity\\Judging', NULL, 'Cannot autowire service ".service_locator.2xMcASS": it references class "App\\Entity\\Judging" but no such service exists.'],
], [
    'jid' => 'App\\Entity\\Judging',
]);
