<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\API\ContestController' shared autowired service.

include_once $this->targetDirs[4].'/lib/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[4].'/lib/vendor/symfony/framework-bundle/Controller/AbstractController.php';
include_once $this->targetDirs[4].'/lib/vendor/friendsofsymfony/rest-bundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[4].'/lib/vendor/friendsofsymfony/rest-bundle/Controller/AbstractFOSRestController.php';
include_once $this->targetDirs[3].'/src/Controller/API/AbstractRestController.php';
include_once $this->targetDirs[3].'/src/Controller/API/ContestController.php';

$this->services['App\\Controller\\API\\ContestController'] = $instance = new \App\Controller\API\ContestController(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->privates['App\\Service\\DOMJudgeService'] ?? $this->getDOMJudgeServiceService()), ($this->privates['App\\Service\\EventLogService'] ?? $this->getEventLogServiceService()), ($this->privates['App\\Service\\ImportExportService'] ?? $this->load('getImportExportServiceService.php')));

$instance->setContainer(($this->privates['.service_locator.uHzIXYg'] ?? $this->load('get_ServiceLocator_UHzIXYgService.php'))->withContext('App\\Controller\\API\\ContestController', $this));

return $instance;
