<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine.fixtures_load_command' shared service.

include_once $this->targetDirs[4].'/lib/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[4].'/lib/vendor/doctrine/doctrine-bundle/Command/DoctrineCommand.php';
include_once $this->targetDirs[4].'/lib/vendor/doctrine/doctrine-fixtures-bundle/Command/LoadDataFixturesDoctrineCommand.php';
include_once $this->targetDirs[4].'/lib/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Loader.php';
include_once $this->targetDirs[4].'/lib/vendor/symfony/doctrine-bridge/DataFixtures/ContainerAwareLoader.php';
include_once $this->targetDirs[4].'/lib/vendor/doctrine/doctrine-fixtures-bundle/Loader/SymfonyFixturesLoader.php';
include_once $this->targetDirs[4].'/lib/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/FixtureInterface.php';
include_once $this->targetDirs[4].'/lib/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/SharedFixtureInterface.php';
include_once $this->targetDirs[4].'/lib/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/AbstractFixture.php';
include_once $this->targetDirs[4].'/lib/vendor/doctrine/doctrine-fixtures-bundle/ORMFixtureInterface.php';
include_once $this->targetDirs[4].'/lib/vendor/doctrine/doctrine-fixtures-bundle/Fixture.php';
include_once $this->targetDirs[4].'/lib/vendor/doctrine/doctrine-fixtures-bundle/FixtureGroupInterface.php';
include_once $this->targetDirs[3].'/src/DataFixtures/AbstractExampleDataFixture.php';
include_once $this->targetDirs[4].'/lib/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/DependentFixtureInterface.php';
include_once $this->targetDirs[3].'/src/DataFixtures/ClarificationFixture.php';
include_once $this->targetDirs[3].'/src/DataFixtures/ContestFixture.php';
include_once $this->targetDirs[3].'/src/DataFixtures/ContestProblemFixture.php';
include_once $this->targetDirs[3].'/src/DataFixtures/ExecutableFixture.php';
include_once $this->targetDirs[3].'/src/DataFixtures/JudgehostFixture.php';
include_once $this->targetDirs[3].'/src/DataFixtures/ProblemFixture.php';
include_once $this->targetDirs[3].'/src/DataFixtures/TeamAffiliationFixture.php';
include_once $this->targetDirs[3].'/src/DataFixtures/TeamCategoryFixture.php';
include_once $this->targetDirs[3].'/src/DataFixtures/TeamFixture.php';
include_once $this->targetDirs[3].'/src/DataFixtures/TestcaseFixture.php';

$a = new \Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader($this);
$a->addFixtures([0 => ['fixture' => new \App\DataFixtures\ClarificationFixture(), 'groups' => []], 1 => ['fixture' => new \App\DataFixtures\ContestFixture(), 'groups' => []], 2 => ['fixture' => new \App\DataFixtures\ContestProblemFixture(), 'groups' => []], 3 => ['fixture' => new \App\DataFixtures\ExecutableFixture(($this->targetDirs[4].'/sql')), 'groups' => []], 4 => ['fixture' => new \App\DataFixtures\JudgehostFixture(), 'groups' => []], 5 => ['fixture' => new \App\DataFixtures\ProblemFixture($this->targetDirs[3]), 'groups' => []], 6 => ['fixture' => new \App\DataFixtures\TeamAffiliationFixture(), 'groups' => []], 7 => ['fixture' => new \App\DataFixtures\TeamCategoryFixture(), 'groups' => []], 8 => ['fixture' => new \App\DataFixtures\TeamFixture(), 'groups' => []], 9 => ['fixture' => new \App\DataFixtures\TestcaseFixture(), 'groups' => []]]);

$this->privates['doctrine.fixtures_load_command'] = $instance = new \Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand($a, ($this->services['doctrine'] ?? $this->getDoctrineService()));

$instance->setName('doctrine:fixtures:load');

return $instance;
