#!/bin/sh
set -e
# Automatically added by dh_installinit/12
if [ -x "/etc/init.d/supervisor" ] && [ "$1" = remove ]; then
	invoke-rc.d supervisor stop || exit 1
fi
# End automatically added section

# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p supervisor 
else
	dpkg -L supervisor | grep '\.py$' | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section
