<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.SlKV0Gk' shared service.

return $this->privates['.service_locator.SlKV0Gk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'zip' => ['privates', '.errored..service_locator.SlKV0Gk.ZipArchive', NULL, 'Cannot autowire service ".service_locator.SlKV0Gk": it references class "ZipArchive" but no such service exists.'],
], [
    'zip' => 'ZipArchive',
]);
