<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container562lbxv\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container562lbxv/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container562lbxv.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container562lbxv\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container562lbxv\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '562lbxv',
    'container.build_id' => 'fe69993b',
    'container.build_time' => 1637922130,
], __DIR__.\DIRECTORY_SEPARATOR.'Container562lbxv');
