<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ZR9itak' shared service.

return $this->privates['.service_locator.ZR9itak'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'rejudgingService' => ['privates', 'App\\Service\\RejudgingService', 'getRejudgingServiceService.php', true],
], [
    'rejudgingService' => 'App\\Service\\RejudgingService',
]);
