<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.l_zN.Gu' shared service.

return $this->privates['.service_locator.l_zN.Gu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'scoreboardService' => ['privates', 'App\\Service\\ScoreboardService', 'getScoreboardServiceService', false],
], [
    'scoreboardService' => 'App\\Service\\ScoreboardService',
]);
