<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_rest.exception.controller' shared autowired service.

include_once $this->targetDirs[4].'/lib/vendor/friendsofsymfony/rest-bundle/Controller/ExceptionController.php';
include_once $this->targetDirs[3].'/src/FosRestBundle/ExceptionController.php';
include_once $this->targetDirs[4].'/lib/vendor/friendsofsymfony/rest-bundle/Util/ExceptionValueMap.php';

return $this->services['fos_rest.exception.controller'] = new \App\FosRestBundle\ExceptionController(($this->services['fos_rest.view_handler'] ?? $this->load('getFosRest_ViewHandlerService.php')), new \FOS\RestBundle\Util\ExceptionValueMap([]), false);
