<?php declare(strict_types=1);
// Do not edit this file!
// Use configure with the right parameters, and run 'make' and 'make install'
// Variables you can change are in common-config.php and domserver-config.php

// Generated from 'domserver-static.php.in' on Wed Feb 19 07:43:20 UTC 2020.

define('DOMJUDGE_VERSION', '7.2.0');

define('BINDIR',      '/opt/domjudge/domserver/bin');
define('ETCDIR',      '/opt/domjudge/domserver/etc');
define('WEBAPPDIR',   '/opt/domjudge/domserver/webapp');
define('LIBDIR',      '/opt/domjudge/domserver/lib');
define('SQLDIR',      '/opt/domjudge/domserver/sql');
define('LIBVENDORDIR','/opt/domjudge/domserver/lib/vendor');
define('LOGDIR',      '/opt/domjudge/domserver/log');
define('RUNDIR',      '/opt/domjudge/domserver/run');
define('TMPDIR',      '/opt/domjudge/domserver/tmp');
define('SUBMITDIR',   '/opt/domjudge/domserver/submissions');

define('BASEURL',     'http://localhost/');

define('SUBMITCLIENT_ENABLED', 'yes');
